name: check-watermark
on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-watermark:
    if: github.actor != 'github-actions[bot]' # avoid loops
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          # Install minimal OpenCV dependencies (headless operation)
          sudo apt-get install -y \
            libglib2.0-0 \
            libgomp1 \
            python3-opencv \
            ffmpeg \
            libsm6 \
            libxext6 \
            libfontconfig1 \
            libxrender1

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify watermarks on all images
        run: |
          set -e

          # Get all image files in the repository
          files=$(git ls-files | grep -Ei '\.(jpe?g|png|webp)$' || true)

          if [ -z "$files" ]; then
            echo "No images found in repository."
            exit 0
          fi

          echo "Checking $(echo "$files" | wc -l) images for watermarks..."

          # Use the watermark script to verify all images
          if python .githooks/watermark.py verify $files; then
            echo "✓ All images have valid watermarks!"
          else
            echo "✗ Some images are missing watermarks!"
            exit 1
          fi
